
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Totoros
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        valueLoaded = 0.0;
        operatorPressed = false;
        operatorPerformed = ' ';
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonMult = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        screen = new javax.swing.JTextPane();
        button1 = new javax.swing.JButton();
        buttonDot = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        buttonDiv = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button0 = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        buttonMinus = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        buttonEqual = new javax.swing.JButton();
        buttonPlus = new javax.swing.JButton();
        buttonSquare = new javax.swing.JButton();
        buttonSquareRoot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonMult.setText("*");
        buttonMult.setMaximumSize(new java.awt.Dimension(10, 10));
        buttonMult.setMinimumSize(new java.awt.Dimension(10, 10));
        buttonMult.setPreferredSize(new java.awt.Dimension(35, 35));
        buttonMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMultActionPerformed(evt);
            }
        });

        screen.setText("0");
        jScrollPane1.setViewportView(screen);

        button1.setText("1");
        button1.setMaximumSize(new java.awt.Dimension(10, 10));
        button1.setMinimumSize(new java.awt.Dimension(10, 10));
        button1.setPreferredSize(new java.awt.Dimension(35, 35));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        buttonDot.setText(".");
        buttonDot.setMaximumSize(new java.awt.Dimension(10, 10));
        buttonDot.setMinimumSize(new java.awt.Dimension(10, 10));
        buttonDot.setPreferredSize(new java.awt.Dimension(35, 35));
        buttonDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDotActionPerformed(evt);
            }
        });

        button5.setText("5");
        button5.setMaximumSize(new java.awt.Dimension(10, 10));
        button5.setMinimumSize(new java.awt.Dimension(10, 10));
        button5.setPreferredSize(new java.awt.Dimension(35, 35));
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        buttonDiv.setText("/");
        buttonDiv.setMaximumSize(new java.awt.Dimension(10, 10));
        buttonDiv.setMinimumSize(new java.awt.Dimension(10, 10));
        buttonDiv.setPreferredSize(new java.awt.Dimension(35, 35));
        buttonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDivActionPerformed(evt);
            }
        });

        button3.setText("3");
        button3.setMaximumSize(new java.awt.Dimension(10, 10));
        button3.setMinimumSize(new java.awt.Dimension(10, 10));
        button3.setPreferredSize(new java.awt.Dimension(35, 35));
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        button4.setText("4");
        button4.setMaximumSize(new java.awt.Dimension(10, 10));
        button4.setMinimumSize(new java.awt.Dimension(10, 10));
        button4.setPreferredSize(new java.awt.Dimension(35, 35));
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        button0.setText("0");
        button0.setMaximumSize(new java.awt.Dimension(10, 10));
        button0.setMinimumSize(new java.awt.Dimension(10, 10));
        button0.setPreferredSize(new java.awt.Dimension(35, 35));
        button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button0ActionPerformed(evt);
            }
        });

        button7.setText("7");
        button7.setMaximumSize(new java.awt.Dimension(10, 10));
        button7.setMinimumSize(new java.awt.Dimension(10, 10));
        button7.setPreferredSize(new java.awt.Dimension(35, 35));
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        button6.setText("6");
        button6.setMaximumSize(new java.awt.Dimension(10, 10));
        button6.setMinimumSize(new java.awt.Dimension(10, 10));
        button6.setPreferredSize(new java.awt.Dimension(35, 35));
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        button2.setText("2");
        button2.setMaximumSize(new java.awt.Dimension(10, 10));
        button2.setMinimumSize(new java.awt.Dimension(10, 10));
        button2.setPreferredSize(new java.awt.Dimension(35, 35));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button9.setText("9");
        button9.setMaximumSize(new java.awt.Dimension(10, 10));
        button9.setMinimumSize(new java.awt.Dimension(10, 10));
        button9.setPreferredSize(new java.awt.Dimension(35, 35));
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });

        buttonMinus.setText("-");
        buttonMinus.setMaximumSize(new java.awt.Dimension(10, 10));
        buttonMinus.setMinimumSize(new java.awt.Dimension(10, 10));
        buttonMinus.setPreferredSize(new java.awt.Dimension(35, 35));
        buttonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMinusActionPerformed(evt);
            }
        });

        button8.setText("8");
        button8.setMaximumSize(new java.awt.Dimension(10, 10));
        button8.setMinimumSize(new java.awt.Dimension(10, 10));
        button8.setPreferredSize(new java.awt.Dimension(35, 35));
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });

        buttonEqual.setText("=");
        buttonEqual.setMaximumSize(new java.awt.Dimension(10, 10));
        buttonEqual.setMinimumSize(new java.awt.Dimension(10, 10));
        buttonEqual.setPreferredSize(new java.awt.Dimension(35, 35));
        buttonEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEqualActionPerformed(evt);
            }
        });

        buttonPlus.setText("+");
        buttonPlus.setMaximumSize(new java.awt.Dimension(10, 10));
        buttonPlus.setMinimumSize(new java.awt.Dimension(10, 10));
        buttonPlus.setPreferredSize(new java.awt.Dimension(35, 35));
        buttonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlusActionPerformed(evt);
            }
        });

        buttonSquare.setText("x^2");
        buttonSquare.setPreferredSize(new java.awt.Dimension(73, 35));
        buttonSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSquareActionPerformed(evt);
            }
        });

        buttonSquareRoot.setText("x^1/2");
        buttonSquareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSquareRootActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonMult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonDot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEqual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSquareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(buttonSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonMult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonDot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonEqual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSquareRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        // TODO add your handling code here:
        String screenText = screen.getText();
        if (operatorPressed){
            screen.setText("8");
            operatorPressed = false;
        }
        else{
            if (screenText.equals("0"))
                screen.setText("8");
            else{
                screenText += 8;
                screen.setText(screenText);
            }
        }
    }//GEN-LAST:event_button8ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        String screenText = screen.getText();
        if (operatorPressed){
            screen.setText("1");
            operatorPressed = false;
        }
        else{
            if (screenText.equals("0"))
                screen.setText("1");
            else{
                screenText += 1;
                screen.setText(screenText);
            }
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        String screenText = screen.getText();
        if (operatorPressed){
            screen.setText("2");
            operatorPressed = false;
        }
        else{
            if (screenText.equals("0"))
                screen.setText("2");
            else{
                screenText += 2;
                screen.setText(screenText);
            }
        }
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        String screenText = screen.getText();
        if (operatorPressed){
            screen.setText("3");
            operatorPressed = false;
        }
        else{
            if (screenText.equals("0"))
                screen.setText("3");
            else{
                screenText += 3;
                screen.setText(screenText);
            }
        }
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
        String screenText = screen.getText();
        if (operatorPressed){
            screen.setText("4");
            operatorPressed = false;
        }
        else{
            if (screenText.equals("0"))
                screen.setText("4");
            else{
                screenText += 4;
                screen.setText(screenText);
            }
        }
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
        String screenText = screen.getText();
        if (operatorPressed){
            screen.setText("5");
            operatorPressed = false;
        }
        else{
            if (screenText.equals("0"))
                screen.setText("5");
            else{
                screenText += 5;
                screen.setText(screenText);
            }
        }
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
        String screenText = screen.getText();
        if (operatorPressed){
            screen.setText("6");
            operatorPressed = false;
        }
        else{
            if (screenText.equals("0"))
                screen.setText("6");
            else{
                screenText += 6;
                screen.setText(screenText);
            }
        }
    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        // TODO add your handling code here:
        String screenText = screen.getText();
        if (operatorPressed){
            screen.setText("7");
            operatorPressed = false;
        }
        else{
            if (screenText.equals("0"))
                screen.setText("7");
            else{
                screenText += 7;
                screen.setText(screenText);
            }
        }
    }//GEN-LAST:event_button7ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        // TODO add your handling code here:
        String screenText = screen.getText();
        if (operatorPressed){
            screen.setText("9");
            operatorPressed = false;
        }
        else{
            if (screenText.equals("0"))
                screen.setText("9");
            else{
                screenText += 9;
                screen.setText(screenText);
            }
        }
    }//GEN-LAST:event_button9ActionPerformed

    private void buttonDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDotActionPerformed
        // TODO add your handling code here:
        String screenText = screen.getText();
        if (operatorPressed){
            screen.setText("0.");
            operatorPressed = false;
        }
        else{
            if (screenText.equals(""))
                screen.setText("0.");
            else{
                if (!screenText.contains(".")) {
                    screenText += '.';
                    screen.setText(screenText);
                }
            }
        }
    }//GEN-LAST:event_buttonDotActionPerformed

    private void button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button0ActionPerformed
        // TODO add your handling code here:
        String screenText = screen.getText();
        if (operatorPressed){
            operatorPressed = false;
        }
        else{
            if (screenText.equals("0")){}
            else{
                screenText += 0;
                screen.setText(screenText);
            }
        }
    }//GEN-LAST:event_button0ActionPerformed

    private void buttonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlusActionPerformed
        // TODO add your handling code here:
        Double num = Double.parseDouble(screen.getText());
        valueLoaded = num;
        operatorPressed = true;
        operatorPerformed = '+';
    }//GEN-LAST:event_buttonPlusActionPerformed

    private void buttonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMinusActionPerformed
        // TODO add your handling code here:
        Double num = Double.parseDouble(screen.getText());
        valueLoaded = num;
        operatorPressed = true;
        operatorPerformed = '-';
    }//GEN-LAST:event_buttonMinusActionPerformed

    private void buttonMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMultActionPerformed
        // TODO add your handling code here:
        Double num = Double.parseDouble(screen.getText());
        valueLoaded = num;
        operatorPressed = true;
        operatorPerformed = '*';
    }//GEN-LAST:event_buttonMultActionPerformed

    private void buttonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDivActionPerformed
        // TODO add your handling code here:
        Double num = Double.parseDouble(screen.getText());
        valueLoaded = num;
        operatorPressed = true;
        operatorPerformed = '/';
    }//GEN-LAST:event_buttonDivActionPerformed

    private void buttonEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEqualActionPerformed
        // TODO add your handling code here:
        switch (operatorPerformed){
            case '+': screen.setText(Double.toString(Operators.addition(valueLoaded, Double.parseDouble(screen.getText())))); 
                break;
            case '-': screen.setText(Double.toString(Operators.subtraction(valueLoaded, Double.parseDouble(screen.getText()))));
                break;
            case '*': screen.setText(Double.toString(Operators.multiplication(valueLoaded, Double.parseDouble(screen.getText()))));
                break;
            case '/':try {
                screen.setText(Double.toString(Operators.division(valueLoaded, Double.parseDouble(screen.getText()))));
                } catch (DivisionByZeroException ex) {
                    Logger.getLogger(Calculator.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            default: try {
                throw new NoOperationPerformed("No operator button has been pressed");
            } catch (NoOperationPerformed ex) {
                Logger.getLogger(Calculator.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonEqualActionPerformed

    private void buttonSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSquareActionPerformed
        // TODO add your handling code here:
        screen.setText(Double.toString(Operators.square(Double.parseDouble(screen.getText()))));
    }//GEN-LAST:event_buttonSquareActionPerformed

    private void buttonSquareRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSquareRootActionPerformed
        // TODO add your handling code here:
        Double num = Double.parseDouble(screen.getText());
        if (num<0){
            try {
                throw new BadInputForSquareRootException("Only positive numbers have square root");
            } catch (BadInputForSquareRootException ex) {
                Logger.getLogger(Calculator.class.getName()).log(Level.SEVERE, null, ex);
            }
            finally{
                screen.setText("NaN");
            }
        }
        else
            screen.setText(Double.toString(Operators.squareRoot(Double.parseDouble(screen.getText()))));
    }//GEN-LAST:event_buttonSquareRootActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }
    
    private Double valueLoaded;
    private Boolean operatorPressed;
    private char operatorPerformed;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton buttonDiv;
    private javax.swing.JButton buttonDot;
    private javax.swing.JButton buttonEqual;
    private javax.swing.JButton buttonMinus;
    private javax.swing.JButton buttonMult;
    private javax.swing.JButton buttonPlus;
    private javax.swing.JButton buttonSquare;
    private javax.swing.JButton buttonSquareRoot;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane screen;
    // End of variables declaration//GEN-END:variables
}
